apiVersion: "v1"
kind: Pod
metadata:
  name: helloworld
  labels:
    release: V76
    app: helloworld-dfasd
spec:
  containers:
    - name: aci-helloworld
      image: dz1workshopacr.azurecr.io/helloacrtasks:v2
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "256Mi"
          cpu: "200m"
