apiVersion: "v1"
kind: Pod
metadata:
  name: helloworld
  labels:
    name: helloworld
    app: helloworld
spec:
  containers:
    - name: aci-helloworld
      image: aksacrdev.azurecr.io/aci-helloworld:v1
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "256Mi"
          cpu: "1000m"