trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionConnectionName: 'defaultAzure'
  helmVersion: 3.1.0

stages:
- stage: Build
  displayName: Build containers, package helm chart, push all
  jobs:
  - job: Build
    displayName: Run build script from repo
    steps:
    - task: HelmInstaller@0
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersion: $(helmVersion)
        checkLatestHelmVersion: false
    - task: Bash@3
      displayName: set executable bit
      inputs:
        targetType: 'inline'
        script: chmod +x scripts/build_multicalculator.sh
    - task: AzureCLI@1
      displayName: 'run build script'
      inputs:
        azureSubscription: $(azureSubscriptionConnectionName)
        scriptPath: scripts/build_multicalculator.sh
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: scripts'
      inputs:
        PathtoPublish: scripts/deploy_multicalulator.sh
        ArtifactName: scripts

- stage: Deploy
  displayName: Deploy containers using helm chart and containers from ACR
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy everything using the deployment script
    environment: 'DevEnvironment1'
    strategy:
     runOnce:
         deploy:
            steps:
            - task: HelmInstaller@0
              displayName: 'Install Helm $(helmVersion)'
              inputs:
                helmVersion: $(helmVersion)
                checkLatestHelmVersion: false
            - task: AzureCLI@1
              displayName: 'set executable bit on scripts'
              inputs:
                azureSubscription: $(azureSubscriptionConnectionName)
                scriptLocation: inlineScript
                inlineScript: |
                    az --version
                    az account show
                    pwd 
                    chmod +x scripts/deploy_multicalulator.sh
            - task: AzureCLI@1
              displayName: 'run build script'
              inputs:
                azureSubscription: $(azureSubscriptionConnectionName)
                scriptPath: scripts/deploy_multicalulator.sh