trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionConnectionName: 'defaultAzure'
  helmVersion: 3.1.0

stages:
- stage: Build
  displayName: Build containers, package helm chart, push all
  jobs:
  - job: Build
    displayName: Run build script from repo
    steps:
    - task: HelmInstaller@0
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersion: $(helmVersion)
        checkLatestHelmVersion: false
    - task: AzureKeyVault@1
      displayName: 'Retrieve secrets from Azure KeyVault'
      inputs:
        azureSubscription: $(azureSubscriptionConnectionName)
        KeyVaultName: $(AZURE_KEYVAULT_NAME)
        secretsFilter: 'phoenixacrname'
    - task: Bash@3
      displayName: echo secret value
      inputs:
        targetType: 'inline'
        script: echo $phoenixacrname
    - task: Bash@3
      displayName: set executable bit
      inputs:
        targetType: 'inline'
        script: chmod +x scripts/build_multicalculator.sh
    - task: AzureCLI@1
      displayName: 'run build script'
      inputs:
        azureSubscription: $(azureSubscriptionConnectionName)
        scriptPath: scripts/build_multicalculator.sh
        arguments: '$(phoenixacrname)'
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: scripts'
      inputs:
        PathtoPublish: scripts/deploy_multicalulator.sh
        ArtifactName: scripts

- stage: Deploy
  displayName: Deploy containers using helm chart and containers from ACR
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy everything using the deployment script
    environment: 'DevEnvironment1'
    strategy:
     runOnce:
         deploy:
            steps:
            - task: HelmInstaller@0
              displayName: 'Install Helm $(helmVersion)'
              inputs:
                helmVersion: $(helmVersion)
                checkLatestHelmVersion: false
            - task: AzureCLI@2
              displayName: Azure CLI
              inputs:
                azureSubscription: $(azureSubscriptionConnectionName)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                    az --version
                    az account show
                    ls -l
            - task: AzureCLI@1
              displayName: 'run build script'
              inputs:
                azureSubscription: $(azureSubscriptionConnectionName)
                scriptPath: $(System.DefaultWorkingDirectory)/_denniszielke.phoenix/scripts/deploy_multicalulator.sh
                workingDirectory: '$(Build.SourcesDirectory)'