name: aci-helloworld

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: |
        ls -l
        echo "Docker login"
        docker login $ACR_NAME -p $ACR_PASSWORD
        echo "Running docker build"
        docker build . --file apps/aci-helloworld/ACR.Dockerfile --tag $ACR_NAME/aci-helloworld:latest
        echo "Pushing image"
        docker push $ACR_NAME/aci-helloworld:latest
        echo "Done"
